# Aplicação
spring.application.name=tasks
#spring.profiles.active=test
##spring.profiles.active=prod
##spring.profiles.active=dev

#Banco de Dados MySQL
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/tarefas
spring.datasource.url=jdbc:mysql://192.168.1.10:3306/tarefas?useSSL=false
spring.datasource.username=ext
spring.datasource.password=ext2025

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.open-in-view=true

#Formato de Data Hora
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.serialization.write-dates-as-timestamps=false